name: 'Deploy'

env:
  GLOBAL_VARIABLE: 'ThisIsaGlobalVariable'

on:
  workflow_dispatch:

  repository_dispatch:
    types: [deploy-automated]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: recursive
      
      - name: "Execute script"
        run: |
          set -ex
          bash ./deploy.sh
        env:
          STEP_VARIABLE: 'ThisIsaStepSpecificVariable'

      - name: "Execute script"
        if: ${{ github.event.client_payload }}
        run: |
          set -ex
          bash ./deploy.sh
        env:
          STEP_VARIABLE: "${{ github.event.client_payload.status }}"