name: 'Deploy'

env:
  GLOBAL_VARIABLE: "Thisisaglobalvariable"

on:
  workflow_dispatch:

  repository_dispatch:
    types: [deploy-automated]
  
jobs:
  deploy:
    outputs:
      tagType: ${{ steps.setVar.outputs.tagType }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: recursive
      
      - name: "Set Variable"
        id: setVar
        run: |
          set -ex
          bash ./deploy.sh
          export GLOBAL_VARIABLE="OVERWRITE"
          echo "::set-output name=tagType::$GLOBAL_VARIABLE"
        env:
          STEP_VARIABLE: 'ThisIsaStepSpecificVariable'
          
      - name: "Execute script"
        run: |
          set -ex
          echo $GLOBAL_VARIABLE
          echo ${{ steps.setVar.outputs.tagType }}
