name: 'Deploy'

env:
  GLOBAL_VARIABLE: 'ThisIsaGlobalVariable'

on:
  workflow_dispatch:

  repository_dispatch:
    types: [deploy-automated]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: recursive
      
      - name: "Execute script"
        run: |
          set -ex
          bash ./deploy.sh
        env:
          STEP_VARIABLE: 'ThisIsaStepSpecificVariable'

      - name: "Execute script"
        if: ${{ github.event.client_payload }}
        run: |
          set -ex
          bash ./deploy.sh
        env:
          STEP_VARIABLE: "${{ github.event.client_payload.status }}"

      - id: set_inital_state
        if: always()
        name: Set initial deployment status
        uses: rsotnychenko/deployment-status-update@0.2.0
        with:
          status: ${{ github.event.client_payload.status }}
          run_id: ${{ github.event.client_payload.run_id }}
          deployment_status_url: ${{ github.event.client_payload.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: "Execute sleep"
        if: ${{ github.event.client_payload }}
        run: |
          set -ex
          sleep(120)

      - id: set_final_state
        if: always()
        name: Set initial deployment status
        uses: rsotnychenko/deployment-status-update@0.2.0
        with:
          status: 'success'
          run_id: ${{ github.event.client_payload.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}      
