name: 'Merged'

env:
  GLOBAL_VARIABLE: 'ThisIsaGlobalVariable' 

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  prMerged:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: recursive
      
      - name: "Execute script"
        run: |
          set -ex
          bash ./merge_pr.sh
        env:
          STEP_VARIABLE: 'ThisIsaStepSpecificVariable'

#      - name: "Dispatch Deploy"
#        uses: peter-evans/repository-dispatch@v1
#        with:
#          token: ${{ secrets.PAT }}
#          repository: plainenough/testing
#          event-type: deploy-automated
#          client-payload: '{ "status": "pending", "run_id": "${{ github.run_id }}", "url": "https://api.github.com/repos/plainenough/testing/deployments/${{ github.run_id }}/statuses"}'       
        
      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1   
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK }}
